/*
 *
 * CandidateTable constants
 *
 */

export const REQUEST_MORE_DETAILS_REQUESTED =
  'app/CandidateTable/REQUEST_MORE_DETAILS_REQUESTED';
export const REQUEST_MORE_DETAILS_SUCCEEDED =
  'app/CandidateTable/REQUEST_MORE_DETAILS_SUCCEEDED';
export const REQUEST_MORE_DETAILS_FAILURE =
  'app/CandidateTable/REQUEST_MORE_DETAILS_FAILURE';
export const REQUEST_MORE_DETAILS = {
  request: REQUEST_MORE_DETAILS_REQUESTED,
  success: REQUEST_MORE_DETAILS_SUCCEEDED,
  failure: REQUEST_MORE_DETAILS_FAILURE,
};
