/*
 *
 * AdminCandidatesListActions constants
 *
 */

export const COMPANY_ACCOUNTS_DELETE_REQUESTED =
  'app/Data/COMPANY_ACCOUNTS_DELETE_REQUESTED';
export const COMPANY_ACCOUNTS_DELETE_FAILED =
  'app/Data/COMPANY_ACCOUNTS_DELETE_FAILED';
export const COMPANY_ACCOUNTS_DELETE_SUCCEEDED =
  'app/Data/COMPANY_ACCOUNTS_DELETE_SUCCEEDED';
export const COMPANY_ACCOUNTS_DELETE = {
  request: COMPANY_ACCOUNTS_DELETE_REQUESTED,
  success: COMPANY_ACCOUNTS_DELETE_SUCCEEDED,
  failure: COMPANY_ACCOUNTS_DELETE_FAILED,
};
