/*
 *
 * Account constants
 *
 */

export const ACCOUNT_DELETE_REQUESTED = 'app/DATA/ACCOUNT_DELETE_REQUESTED';
export const ACCOUNT_DELETE_FAILED = 'app/DATA/ACCOUNT_DELETE_FAILED';
export const ACCOUNT_DELETE_SUCCEEDED = 'app/DATA/ACCOUNT_DELETE_SUCCEEDED';
